version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: yummycli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/yummysource/yummycli/internal/build.Version={{ .Version }}
      - -X github.com/yummysource/yummycli/internal/build.Date={{ .Date }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "yummycli-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

release:
  github:
    owner: yummysource
    name: yummycli
